import { existsSync, mkdirSync, readdirSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { loadManifest } from "./lib/manifest.ts";
import { scanSubmodule } from "./lib/scan.ts";

const root = process.cwd();
const curated = new Map<string, string>();
const curationDir = join(root, "curation");
if (existsSync(curationDir)) {
  for (const f of readdirSync(curationDir).filter((f) => f.endsWith(".yaml"))) {
    const m = loadManifest(join(curationDir, f));
    for (const item of m.items) {
      curated.set(item.source, item.exclude ? "excluded" : m.plugin.name);
    }
  }
}

let md = "# Skill Inventory\n\nGenerated by `npm run inventory`. Do not edit by hand.\n";
for (const sub of readdirSync(join(root, "external")).sort()) {
  const comps = scanSubmodule(join(root, "external"), sub).sort(
    (a, b) => a.type.localeCompare(b.type) || a.name.localeCompare(b.name),
  );
  md += `\n## ${sub} — ${comps.length} components\n\n| Name | Type | Curated | Description | Source | Files | KB |\n|---|---|---|---|---|---|---|\n`;
  for (const c of comps) {
    const desc = c.description.replaceAll("|", "\\|").replaceAll("\n", " ").slice(0, 140);
    md += `| ${c.name} | ${c.type} | ${curated.get(c.sourcePath) ?? "—"} | ${desc} | \`${c.sourcePath}\` | ${c.files} | ${Math.ceil(c.bytes / 1024)} |\n`;
  }
}
mkdirSync(join(root, "docs"), { recursive: true });
writeFileSync(join(root, "docs", "inventory.md"), md);
console.log("Wrote docs/inventory.md");
